### ISSUE TITLE
Remove this useless assignment to local variable

### ISSUE THREAD

**Issue by Willshield** [don-IET/Habito#10]
Two usless assignmet found by SonarQube in:
src/.../com/ivanmagda/habito/widget/DetailWidgetRemoteViewsService.java 
src/.../com/ivanmagda/habito/utils/ColorUtils.java

**Comment by Willshield** [comment]
ColorUtils.java had an uncompleted and unused method. Method fixed, now the assignment is not useless.

**Comment by Willshield** [comment]
Issue fixed

**Comment by kszabi51** [comment]
Issue reviewed!
