### ISSUE TITLE
Fix division operation

### ISSUE THREAD

**Issue by Willshield** [don-IET/Habito#12]
Cast operands to double to get the good result
Issue found in:
 src/.../com/ivanmagda/habito/barchart/HabitoBarChartConfigurator.java

**Comment by Willshield** [comment]
Minor fix implemented

**Comment by micskeiz** [comment]
Try to link the commits with the issue (either by adding here as a comment or by referencing the issue in the commit message).

**Comment by Willshield** [comment]
Division operation fix implemented in this commit:
https://github.com/don-IET/Habito/commit/ecb301ca28ecf2b6a70d7ff16b52859b6ebc7adf
