### ISSUE TITLE
Make "FORMATTER" an instance variable.

### ISSUE THREAD

**Issue by Willshield** [don-IET/Habito#8]
Bug appeared in 3 java files. Minor fixes needed. Problems found in:
src/.../habito/barchart/formatters/MonthAxisValueFormatter.java 
src/.../habito/barchart/formatters/YearAxisValueFormatter.java 
src/.../ivanmagda/habito/barchart/view/XYMarkerView.java

**Comment by Willshield** [comment]
Found more similar bug in:
src/.../habito/barchart/formatters/WeekDayAxisValueFormatter.java
src/.../com/ivanmagda/habito/models/ReminderTime.java 
src/.../ivanmagda/habito/view/model/HabitListItemViewModel.java

**Comment by Willshield** [comment]
3 more similar bug in:
 src/.../ivanmagda/habito/view/model/HabitDetailViewModel.java

**Comment by Willshield** [comment]
All localizable global static members fixed.

**Comment by kszabi51** [comment]
Fix reviewed!

**Comment by Willshield** [comment]
Issue fixed in this commit:
https://github.com/don-IET/Habito/commit/026d7f9beae076c2ce8e553290f54da6e0131351
